sudo: required
services:
    - docker

before_install:
    - docker build -t miloscpt/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true miloscpt/react-test npm test

after_success:
    - docker build -t miloscpt/multicc-client ./client
    - docker build -t miloscpt/multic-nginx  ./nginx
    - docker build -t miloscpt/multic-server ./server
    - docker build -t miloscpt/multic-worker ./worker
    # login into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take images and push them to Docker Hub
    - docker push miloscpt/multicc-client
    - docker push miloscpt/multic-nginx
    - docker push miloscpt/multic-server
    - docker push miloscpt/multic-worker